---
title: "Community Factors in MOUD Sites"
author: "Sam Jaros"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
# Package install
require(lubridate)
require(table1)
require(tidyverse)
source(here::here("code/__utils.R"))

# Settings
dna = NA #4 makes neutral, NA makes it missing
survey_date = ymd("2022-09-01")
```

# Load Data

```{r data}
#Get info for whether studies were included in MMCS and whether they did an interview
mmcs_info = read_csv(here::here("raw_data/mmcs_info.csv"))
  
# Get CDI from API, not excluding studies that later dropped out
cdi_questions_of_interest = paste0("0",3:8)
cdi_scoring = read_csv(here::here("public_data/cdi_scoring.csv"))
cdi = bind_rows(get_redcap_report("SC", "110001"), 
                get_redcap_report("PC", "110006")) %>%
  select(program_id, redcap_event_name, starts_with("cdi_")) %>%
  pivot_longer(c(starts_with("cdi_"),-"cdi_team_report_timestamp"),
               names_to="item",
               values_to="value", 
               values_drop_na=T) %>%
  # Bring in scoring information
  left_join(cdi_scoring, by="item") %>%
  # Put score in terms of centered around 0
  # Modify missing as needed
  # Reverse scales where needed
  mutate(centered_score = case_when(value==8  ~ dna-4, 
                                    isReverse ~ (value-4)*-1, 
                                    T         ~ value-4),
         score = centered_score+4) %>%
  mutate(date = fast_strptime(str_extract(redcap_event_name, 
                                          "^([a-z]*_[0-9]*)"), "%b_%Y"))%>%
  # Get only the observations & variables needed for MMCS
  filter(date==survey_date) %>%
  filter(q_num %in% cdi_questions_of_interest) %>%
  pivot_wider(id_cols = c(program_id, date),
              names_from = q_num,
              names_prefix = "cdi_",
              values_from = score)

# Get IMAT data directly from API
imat = bind_rows(get_redcap_report("SC", "119747") %>%
                   mutate(across(contains("_count_"), ~as.character(.x))),
                 get_redcap_report("PC", "119745") %>%
                   mutate(across(contains("_count_"), ~as.character(.x)))) %>%
  # Remove incomplete surveys (completion!=2)
  filter(imatpc_team_report_complete==2 | imatsc_team_report_complete==2) %>%
  # Get survey date from redcap event
  mutate(date = my(substr(redcap_event_name, 1, 8))) %>%
  filter(date==survey_date) %>%
  select(program_id, date, imat_d5_6)

program_info = readRDS(here::here("data/all_program_info.rds"))

study_data = mmcs_info %>%
  left_join(full_join(cdi, imat, by=c("program_id", "date")) %>%
              full_join(program_info, by="program_id")) %>%
  filter(in_mmcs,
         !(program_id %in% paste0("id",54:62)))
```

# Summary Stats

```{r summary_stats}
table1(~site_type + care_level + urbanity | factor(did_interview),
       data=study_data)

# Get mean question scores
study_data %>%
  mutate(imat_d5_6 = case_match(imat_d5_6,
                                1 ~ 1,
                                2 ~ 2.5,
                                3 ~ 4,
                                4 ~ 5.5,
                                5 ~ 7,
                                .default=NA)) %>%
  summarize(across(cdi_03:imat_d5_6, 
                   list(mean=~mean(.x,, na.rm=T), sd=~sd(.x, na.rm=T)),
                   .names="{.col}!{.fn}")) %>%
  pivot_longer(cols=everything(),
               names_pattern = "(.*)!(.*)",
               names_to = c("question",".value"))


```

# Chronbach Alpha

```{r chron_alpha}
require(ltm)
c_alpha = cronbach.alpha(study_data %>% 
                           dplyr::select(cdi_03:imat_d5_6) %>% 
                           drop_na())
c_alpha

# Remove MASS package to avoid conflicts with dplyr
detach("package:ltm", unload=T)
detach("package:MASS", unload=T)
```

# Principal components analysis

```{r regression}
pc_analysis = prcomp(study_data %>%
         select(starts_with("cdi_"), starts_with("imat_")) %>%
         drop_na(), 
       scale.=T)
summary(pc_analysis)
pc_analysis$rotation
```

